### ISSUE TITLE
Occasional issue with thermostat set temps showing up as 100*

### ISSUE THREAD

**Issue by shaferz** [jgulick48/rv-homekit#15]
Simply documenting this for now until I can get screenshots.

Sometimes when opening the Home app on my iphone, the 'set temperature' of thermostats is showing as 100*.  The state (heating/cooling/off) of the thermostat does correctly show up, but the 'set temperature' defaults to 100*.  In the last cases where I saw this, the a/c was already running and showing the correct set temp in the OneControl app, but RVHomekit thinks the set temp is 100*.  Next time I see this happen, I will update this issue with screenshots.

**Comment by jgulick48** [comment]
This happens when the container startsup when an AC unit is set to off.  I've fixed this in the latest release release-arm-0.0.12-rc133

**Comment by shaferz** [comment]
@jgulick48, I'm still seeing v0.0.11 as the latest release.
