### ISSUE TITLE
Thermostat temps stuck at 50*

### ISSUE THREAD

**Issue by shaferz** [jgulick48/rv-homekit#7]
The LCI apps and LCI web portal are reporting temps of 35-36*F but HomeKit sees 50* across all thermostats.  

HomeKit does appear to correctly grab the thermostat state, but the temperature readings are all stuck at 50*.

Any ideas? 

Screenshots attached.  

![F72DB1EB-47F3-409E-B9DA-E37F228E4328](https://user-images.githubusercontent.com/72487172/103723881-afeb7880-4f98-11eb-8382-3f3b9918c1df.png)

![3E233CD5-6769-41B3-A519-26918B633397](https://user-images.githubusercontent.com/72487172/103723901-ba0d7700-4f98-11eb-922a-ff32b72801c1.png)

**Comment by jgulick48** [comment]
For practical reasons Homekit has a minimum and maximum temp that thermostats can report/be set to. I can either expand this range or make it configurable pretty easily. Let me know your preference.

**Comment by shaferz** [comment]
Oh cool.  Are ‘Current Temp’ and ‘Desired Temp’ two different ranges?  Or is it just a single range?

**Comment by jgulick48** [comment]
It is a single range on homekit.

**Comment by shaferz** [comment]
Ah, that is too bad.  With that being said, and if possible, maybe it would be best to make the range configurable?  The base configuration could be whatever range is used currently, but then allow a user to update this to match their location if desired?
